local PATH = ""

NETWORK.voice.RegisterCategory("cporder", "voiceCPOrder")
NETWORK.voice.RegisterCategory("cpcode", "voiceCPCode")
NETWORK.voice.RegisterCategory("cpstatus", "voiceCPStatus")
NETWORK.voice.RegisterCategory("cpcombat", "voiceCPCombat")
NETWORK.voice.RegisterCategory("cpnumber", "voiceCPNumber")
NETWORK.voice.RegisterCategory("cpmood", "voiceCPMood")
NETWORK.voice.RegisterCategory("cpidle", "voiceCPIdle")

local lines = {
	{"0", "Ноль.", "zero.wav", "cpnumber"},
	{"11-99", "11-99, нападение на офицера", "11-99officerneedsassistance.wav", "cpcombat"},
	{"404", "Зона 404, опасность", "404zone.wav", "cpcode"},
	{"наблюдаю", "Наблюдаю субьект", "acquiringonvisual.wav", "cpcombat"},
	{"исполнять", "Исполнять", "administer.wav", "cporder"},
	{"исполнять!", "Исполнять!", "administer2.wav", "cporder"},
	{"следопыт", "Следопыт", "adventurer.wav", "cpcode"},
	{"так точно", "Так точно", "affirmative.wav", "cpstatus"},
	{"так точно!", "Так точно!", "affirmative2.wav", "cpstatus"},
	{"порядок", "Все в порядке, можешь идти", "allrightyoucango.wav", "cpstatus"},
	{"отчесь", "Отсечь", "amputate.wav", "cporder"},
	{"антигражданин", "Антигражданин", "anticitizen.wav", "cpcode"},
	{"вредитель", "Вредитель", "anticitizen2.wav", "cpcode"},
	{"львы", "Муравьиные львы", "antlion.wav", "cpstatus"},
	{"хищник", "Хищник", "apex.wav", "cpcode"},
	{"назовись", "Назовись", "apply.wav", "cporder"},
	{"на точке", "На точке", "atcheckpoint.wav", "cpstatus"},
	{"на месте", "На месте", "atcheckpoint2.wav", "cpstatus"},
	{"назад!", "Назад!", "backup.wav", "cpcombat"},
	{"начеку", "Всем быть начеку!", "beready.wav", "cpstatus"},
	{"начеку1", "Быть начеку, докладывать о любом движении", "bereadyreport.wav", "cpstatus"},
	{"чёрный", "Чёрный", "black.wav", "cpcode"},
	{"клинок", "Клинок", "blade.wav", "cpcode"},
	{"прорвать защиту", "Прорвать защиту!", "breakhiscover.wav", "cpcombat"},
	{"жуки", "Жуки", "bugs.wav", "cpstatus"},
	{"улей", "Улей", "bugs2.wav", "cpstatus"},
	{"рой", "Рой", "bugs3.wav", "cpstatus"},
	{"канал", "Канал", "canal.wav", "cpcode"},
	{"доклад окружение", "Следите за информацией об окружении", "catchthatbliponstabilization.wav", "cpstatus"},
	{"клеймить", "Клеймить", "cauterize.wav", "cporder"},
	{"гражданин", "Гражданин", "citizen.wav", "cpcode"},
	{"гражданин1", "Гражданин!", "citizen2.wav", "cpcode"},
	{"гражданин2", "Граждани... Км, блять. Гражданин!", "citizen3.wav", "cpcode"},
	{"чисто", "Чисто", "clear.wav", "cpstatus"},
	{"код 100", "Код сто", "code100.wav", "cpcode"},
	{"контакт", "Контакт", "contact.wav", "cpcombat"},
	{"заражение", "Заражение", "contagion.wav", "cpstatus"},
	{"понял", "Понял", "copy.wav", "cpstatus"},
	{"кашель1", "Кхе-кхе", "cough.wav", "cpmood"},
	{"кашель2", "Кхе-кхе-кхе", "cough2.wav", "cpmood"},
	{"кашель3", "КХЕ-КХЕК-ХЕ", "cough3.wav", "cpmood"},
	{"укрытие", "Укрытие", "cover.wav", "cpcombat"},
	{"укрытие1", "Укрытие!", "cover2.wav", "cpcombat"},
	{"доклад отклик", "Всем отрядам, произвести отклик и доложить", "cprequestsallunitsreportin.wav", "cpstatus"},
	{"кинжал", "Кинжал", "dagger.wav", "cpcode"},
	{"опасная зона", "Внимание: опасная зона", "dangerzone.wav", "cpstatus"},
	{"мертвец", "Мертвец", "deadman.wav", "cpcode"},
	{"защитник", "Защитник", "defender.wav", "cpcode"},
	{"мерзость", "Мерзость!", "disgust.wav", "cpstatus"},
	{"документы", "Документы", "document.wav", "cporder"},
	{"документы1", "Документы!", "document2.wav", "cporder"},
	{"документы2", "ДОКУМЕНТЫ!", "document3.wav", "cporder"},
	{"не могу знать", "Никак не могу знать", "dontknow.wav", "cpstatus"},
	{"не знаю", "Не знаю", "dontknow2.wav", "cpstatus"},
	{"понятия не имею", "Понятия не имею", "dontknow3.wav", "cpstatus"},
	{"не осведомлен", "Не осведомлён", "dontknow4.wav", "cpstatus"},
	{"не двигаться", "Не двигаться", "dontmove.wav", "cporder"},
	{"стоять", "Стоять!", "dontmove2.wav", "cporder"},
	{"не двигайся", "Не двигаться!", "dontmove3.wav", "cporder"},
	{"эхо", "Эхо", "echo.wav", "cpcode"},
	{"8", "Восемь", "eight.wav", "cpnumber"},
	{"18", "Восемьнадцать", "eighteen.wav", "cpnumber"},
	{"80", "Восемьдесят", "eighty.wav", "cpnumber"},
	{"11", "Одиннадцать", "eleven.wav", "cpnumber"},
	{"проверить", "Проверить", "examine.wav", "cporder"},
	{"просрочен", "Просрочен", "expired.wav", "cporder"},
	{"тяжелое дыхание1", "Ых ах ых ах ых ах", "fastheavybreathing.wav", "cpmood"},
	{"тяжелое дыхание2", "Ыхх уфф", "fastheavybreathing2.wav", "cpmood"},
	{"15", "Пятнадцать", "fifteen.wav", "cpnumber"},
	{"50", "Пятьдесят", "fifty.wav", "cpnumber"},
	{"последнее предупреждение", "Последнее предупреждение!", "finalwarning.wav", "cporder"},
	{"1 предупреждение", "Первое предупреждение", "firstwarningmove.wav", "cporder"},
	{"5", "Пять", "five.wav", "cpnumber"},
	{"вспышка", "Вспышка", "flash.wav", "cpstatus"},
	{"4", "Четыре", "four.wav", "cpnumber"},
	{"14", "Четырнадцать", "fourteen.wav", "cpnumber"},
	{"40", "Сорок", "fourty.wav", "cpnumber"},
	{"го ложись", "Ложись", "getdown.wav", "cporder"},
	{"убирайся1", "Убирайся отсюда", "getoutofhere.wav", "cporder"},
	{"убирайся2", "Убирайся вон", "getoutofhere2.wav", "cporder"},
	{"убирайся!", "Гражданин, если вы сейчас же не уберётесь, я... Сука, чё ты мне мозги делаешь, просто вали нахуй отсюда", "getoutofhere3.wav", "cporder"},
	{"зеленый", "Зелёный", "green.wav", "cpcode"},
	{"граната1", "Граната", "grenade.wav", "cpcombat"},
	{"граната!", "ГРАНАТА!", "grenade2.wav", "cpcombat"},
	{"граната", "Граната!", "grenade3.wav", "cpcombat"},
	{"хаха", "Хахахаха", "haha.wav", "cpmood"},
	{"ха-ха", "Ха-хахаха", "haha2.wav", "cpmood"},
	{"хахаха", "Хехехе", "haha3.wav", "cpmood"},
	{"ха-ха-ха", "Хыхахаха", "haha4.wav", "cpmood"},
	{"хах", "Ха-ха-ха-ха-ха", "haha5.wav", "cpmood"},
	{"хех", "Хыхахахыха", "haha6.wav", "cpmood"},
	{"молот", "Молот", "hammer.wav", "cpcode"},
	{"паразиты", "Паразиты", "headcrabs.wav", "cpstatus"},
	{"паразит", "Паразитарная форма жизни", "headcrabs2.wav", "cpstatus"},
	{"твари", "Ползучие твари", "headcrabs3.wav", "cpstatus"},
	{"крабы", "Головные паразиты", "headcrabs4.wav", "cpstatus"},
	{"дыхание1", "Ых ых ых", "heavybreathing.wav", "cpmood"},
	{"дыхание2", "ЫЫЫЫХ ЭЭЭ... ЫЫЫЫХ ЭЭЭЭ", "heavybreathing2.wav", "cpmood"},
	{"помогите", "Помогите!", "help.wav", "cpcombat"},
	{"нужна помощь", "Мне нужна помощь", "help2.wav", "cpcombat"},
	{"герой", "Гейрой", "hero.wav", "cpcode"},
	{"подожди", "Подожди-ка", "holdit.wav", "cporder"},
	{"охотник", "Охотник", "hunter.wav", "cpstatus"},
	{"охуительная история1", "Да, я помню его. Да нет, притворялся он больным, он при мне дурака включал. Да, всё правильно сделали", "idle.wav", "cpidle"},
	{"охуительная история2", "Вот когда я лежал в лазарете, меня расширенным пайком кормили...", "idle10.wav", "cpidle"},
	{"ни минуты спокойствия", "До чего-ж этот город меня раздражает! Ни минуты спокойствия!", "idle11.wav", "cpidle"},
	{"кпк заряд теряет", "КПК этот неведомо как заряд теряет. Надоело до жути.", "idle12.wav", "cpidle"},
	{"охуительная история3", "Тот потерянный биосигнал до сих пор в моих ушах раздаётся. Теперь даже обсудить нескем. Чёрт", "idle13.wav", "cpidle"},
	{"охуительная история4", "Кто не рискует-тот живёт на пенсии. Ну а деньги необходимы человеку, дабы прекратить о них думать", "idle14.wav", "cpidle"},
	{"охуительная история5", "Не учатся ничему некоторые и учиться не хотят", "idle15.wav", "cpidle"},
	{"охуительная история6", "Достал меня этот город, ух достал! Вот бы отсидеться где... Да не где. Служи-служи, а затем пиздуй на пенсию. С травмами со службы. Тьфу", "idle16.wav", "cpidle"},
	{"охуительная история7", "Карантинная зона... Да мы уже поуши в этой карантинной зоне! Сначала за солдат взялись, а затем за нас. Правда мы уже будем явно слабее, да и продержимся мы не так уж и долго", "idle17.wav", "cpidle"},
	{"охуительная история8", "Дай рабочему миллион токенов и он накупит еды пока не нажрётся. А затем поймёт, что в продаже есть не только брендированная жратва. Аккуратней с деньгами нужно быть, так что правильно всё делают покровители", "idle18.wav", "cpidle"},
	{"охуительная история9", "Плевал я на всё ваше человечество. Во всём человечестве чего-то стою один я. Дерьмо я, как некоторые или стою чего...", "idle19.wav", "cpidle"},
	{"охуительная история10", "Наковальня, испытываю проблемы с визором. Если есть активные плангеры, прибуду на ваши 10-20. 10-4. 10-2. 10-6. Конец связи", "idle2.wav", "cpidle"},
	{"охуительная история11", "Вот иногда смотришь на человека и думаешь: Доплачиваеют ему что-ли? Ну невозможно быть таким долбаёбом по доброй воле!", "idle20.wav", "cpidle"},
	{"охуительная история12", "Мы стоим на краю пропасти перемен. Мир боится неизбежного падения в пропасть. Следите за этим моментом и прыгайте, ведь только когда вы падаете, вы узнаете, умеете ли-вы летать", "idle21.wav", "cpidle"},
	{"охуительная история13", "Слушаю. 10-1. Ваши 10-20. ВАШИ 10-20? Ну вы долбаёбы, нет, ко мне его вести не нужно. 10-2. Просто сохраняйте самообладание, 10-65 в любой ситуации. Включая 10-99. Всё, конец связи, 10-3", "idle3.wav", "cpidle"},
	{"охуительная история14", "Вы сдурели это в рацию говорить!? Да если это 49-му доложат, то он с вас три шкуры симет. Нет, это не является нарушением. Всё, у меня есть дела поважней, конец связи", "idle4.wav", "cpidle"},
	{"охуительная история15", "10-2, ещё 2 раза проверь. Виноват, сорвался. Ещё 2 раза проверьте, внимательно наблюдайте 10-19А. Да если вас эти твари не разорвут, это офицеры сделают. Просто замечательно, а теперь стойте смотрите 10-19. 10-4. Конец связи", "idle5.wav", "cpidle"},
	{"охуительная история16", "Да, я понял о чём вы, но к чему это. Благодарю, но не думаю, что это хорошее место для подобных слов. Серьёзно? Разрешили? Ну вот у вас язык подвешан. Нет, я просто выполнял свой долг. Да этих тварей даже опытные боятся. Да, блокпост устоял сопротивление. 10-2. 10-4. Конец связи", "idle6.wav", "cpidle"},
	{"охуительная история17", "10-1, хорошо что спросили. Да, пошёл на поправку. X-генам пришлось хорошо потрудиться. Да я признаться не думал, что он выживет. Пока его тащили, он литры крови отхаркивал. И нас и контроль заражения они хорошенько натаскивают. 10-3 10-4 10-0.", "idle7.wav", "cpidle"},
	{"охуительная история18", "10-2, не могу никоим образом. ЭТО лучше обсудить лично. Да и не стоит внедрять план, сейчас самый час пик! Поэтому 10-3 и тишина.", "idle8.wav", "cpidle"},
	{"охуительная история19", "Это что ещё за чёрт был? У меня одного поломка рации сейчас была? Какие-то неполадки. Скоро будет плановая проверка оборудования чувствуется. А, 10-4. Хорошо, что не у меня. ПРАВДА? ВЕСЬ АВАНПОСТ СМЯЛО? Резерв включили?", "idle9.wav", "cpidle"},
	{"ненавижу", "Ненавижу эти штуки!", "ihatethesthings.wav", "cpstatus"},
	{"инфекция", "Инфекция", "infection.wav", "cpstatus"},
	{"зона заражения", "Заражённая зона", "infestedzone.wav", "cpstatus"},
	{"задействовать", "Задействовать", "inject.wav", "cporder"},
	{"ранен1", "Я ранен..", "injured1.wav", "cpmood"},
	{"ранен2", "Я ранен", "injured2.wav", "cpmood"},
	{"ранен3", "Я ранен... Эх...", "injured3.wav", "cpmood"},
	{"ранение", "Ранение...", "injured4.wav", "cpmood"},
	{"ранение1", "Получил ранение", "injured5.wav", "cpmood"},
	{"ранен тварью", "Ах, зацепила тварь", "injured6.wav", "cpmood"},
	{"ранен4", "Твою мать, я ранен!", "injured7.wav", "cpmood"},
	{"предотвратить", "Предотвратить", "innoculate.wav", "cporder"},
	{"на позиции", "На позиции", "inposition.wav", "cpstatus"},
	{"расследовать", "Расследовать", "investigate.wav", "cporder"},
	{"отойти", "Я сказал отойти", "isaidmovealong.wav", "cporder"},
	{"отойти1", "Со слухом не впорядке? Я же сказал ОТОЙТИ", "isaidmovealong2.wav", "cporder"},
	{"выдвигаюсь", "Выдвигаюсь", "ismovingin.wav", "cpstatus"},
	{"изолировать", "Изолировать", "isolate.wav", "cporder"},
	{"безопасно", "Здесь безопасно", "itssafehere.wav", "cpstatus"},
	{"судья", "Судья", "jury.wav", "cpcode"},
	{"продолжить движение", "Продолжить движение", "keepmoving.wav", "cporder"},
	{"король", "Король", "king.wav", "cpcode"},
	{"лидер", "Лидер", "leader.wav", "cpcode"},
	{"линия", "Линия", "line.wav", "cpcode"},
	{"локация", "Локация", "location.wav", "cpcode"},
	{"фиксировать", "Фиксировать", "lock.wav", "cporder"},
	{"проблемы1", "В чём дело? Ищешь проблем?", "lookingfortrouble.wav", "cpstatus"},
	{"проблемы2", "Если ты жаждешь наказания, то ты на верном пути", "lookingfortrouble2.wav", "cpstatus"},
	{"осторожно", "Осторожно!", "lookout.wav", "cpcombat"},
	{"двигайся", "Двигайся", "move.wav", "cporder"},
	{"иди", "Иди", "move2.wav", "cporder"},
	{"проходи", "Проходи", "movealong.wav", "cporder"},
	{"назад", "Назад, немедленно!", "movebackrightnow.wav", "cporder"},
	{"некротик", "Некротик", "necrotic.wav", "cpcode"},
	{"помощь?", "Помощь нужна?", "needanyhelpwiththisone.wav", "cpstatus"},
	{"нужна медпомощь", "Нужна медицина", "needmedicine.wav", "cpcombat"},
	{"го нет", "Негативно", "negative.wav", "cpstatus"},
	{"9", "Девять", "nine.wav", "cpnumber"},
	{"19", "Девятнадцать", "ninety.wav", "cpnumber"},
	{"контакта нет1", "Контакт не наблюдаю", "nocontact.wav", "cpcombat"},
	{"контакта нет2", "Не, нихера не вижу", "nocontact2.wav", "cpcombat"},
	{"ничего", "Ничего", "nothing.wav", "cpstatus"},
	{"го убирайся", "А теперь-убирайся", "nowgetoutofhere.wav", "cporder"},
	{"1", "Один", "one.wav", "cpnumber"},
	{"100", "Сто", "onehundred.wav", "cpnumber"},
	{"оранжевый", "Оранжевый", "orange.wav", "cpcode"},
	{"прорыв", "Прорыв", "outbreak.wav", "cpstatus"},
	{"надзор", "Надзор", "overwatch.wav", "cpcode"},
	{"боль1", "Ах!", "pain.wav", "cpmood"},
	{"боль2", "Ахх!", "pain2.wav", "cpmood"},
	{"боль3", "Аххх!", "pain3.wav", "cpmood"},
	{"боль4", "Ай!", "pain4.wav", "cpmood"},
	{"боль5", "Ых!", "pain5.wav", "cpmood"},
	{"боль6", "Аах!", "pain6.wav", "cpmood"},
	{"патруль", "Патруль", "patrol.wav", "cpcode"},
	{"банка1", "Подними эту банку", "pickupthecan1.wav", "cporder"},
	{"банка2", "Подними. Банку.", "pickupthecan2.wav", "cporder"},
	{"банка3", "Я сказал ПОДНИМИ БАНКУ", "pickupthecan3.wav", "cporder"},
	{"да", "Положительно", "positive.wav", "cpstatus"},
	{"вольно", "Вольно", "preserve.wav", "cporder"},
	{"вольно2", "Вольно", "preserve2.wav", "cporder"},
	{"вольно3", "Вольно", "preserve3.wav", "cporder"},
	{"банка4", "А теперь, положи её туда, где ей место", "putitinthetrash1.wav", "cporder"},
	{"быстрей", "Быстрей!", "quick.wav", "cpcombat"},
	{"наготове", "Приготовиться к применению силы", "readyguns.wav", "cpcombat"},
	{"отсечение", "Готов к отсечению", "readytoamputate.wav", "cporder"},
	{"приговор", "Готов вынести приговор", "readytojudge.wav", "cporder"},
	{"пресечение", "Готов к пресечению", "readytoprosecute.wav", "cporder"},
	{"красный", "Красный", "red.wav", "cpcode"},
	{"перезарядка", "Перезарядка!", "reload2.wav", "cpcombat"},
	{"перезарядка1", "Перезарядка", "reloading.wav", "cpcombat"},
	{"запрос медпомощи", "Запрашиваю медицинскую поддержку", "requestmedicalsupport.wav", "cpcombat"},
	{"ограничить", "Ограничить", "restrict.wav", "cporder"},
	{"вас понял", "Вас понял", "rodgerthat.wav", "cpstatus"},
	{"боль7", "Аааааах!!!", "screaminpain.wav", "cpmood"},
	{"искать", "Искать!", "search.wav", "cpcombat"},
	{"2 предупреждение", "Второе предупреждение!", "secondwarning.wav", "cporder"},
	{"сектор", "Сектор", "sector.wav", "cpcode"},
	{"приговор вынесен", "Приговор вынесен", "sentencedelivered.wav", "cporder"},
	{"служить", "Служу покровителям!", "serve.wav", "cpstatus"},
	{"служу1", "Служу вселенскому союзу!", "serve2.wav", "cpstatus"},
	{"служу", "Служу", "serve3.wav", "cpstatus"},
	{"7", "Семь", "seven.wav", "cpnumber"},
	{"17", "Семнадцать", "seventeen.wav", "cpnumber"},
	{"70", "Семьдесят", "seventy.wav", "cpnumber"},
	{"черт", "Чёрт!", "shit.wav", "cpmood"},
	{"твою мать", "Да твою-же мать!", "shit2.wav", "cpmood"},
	{"ебучий случай", "Ебучий случай", "shit3.wav", "cpmood"},
	{"еб твою", "Да ёб твою", "shit4.wav", "cpmood"},
	{"блять", "Блять", "shit5.wav", "cpmood"},
	{"да блять", "Да блять!", "shit6.wav", "cpmood"},
	{"6", "Шесть", "six.wav", "cpnumber"},
	{"16", "Шестнадцать", "sixteen.wav", "cpnumber"},
	{"60", "Шестьдесят", "sixty.wav", "cpnumber"},
	{"стерилизовать", "Стерилизовать", "sterilize.wav", "cporder"},
	{"жезл", "Жезл", "stick.wav", "cpcode"},
	{"стоп!", "Стоп!", "stop!.wav", "cporder"},
	{"стоп", "Стоп", "stop.wav", "cporder"},
	{"субьект", "Субьект", "subject.wav", "cpcode"},
	{"подавлять", "Подавлять", "supress.wav", "cpcombat"},
	{"меч", "Меч", "sword.wav", "cpcode"},
	{"укрытие2", "В укрытие!", "takecover.wav", "cpcombat"},
	{"цель", "Цель", "target.wav", "cpcode"},
	{"10", "Десять", "ten.wav", "cpnumber"},
	{"10-2", "Десять-два", "ten2.wav", "cpnumber"},
	{"10-4", "Десять-четыре", "ten4.wav", "cpnumber"},
	{"жду указаний", "Десять-восемь, жду указаний", "ten8standingby.wav", "cpstatus"},
	{"13", "Тринадцать", "thirteen.wav", "cpnumber"},
	{"30", "Тридцать", "thirty.wav", "cpnumber"},
	{"3", "Три", "three.wav", "cpnumber"},
	{"300", "Триста", "threehundred.wav", "cpnumber"},
	{"12", "Двенадцать", "twelve.wav", "cpnumber"},
	{"20", "Двадцать", "twenty.wav", "cpnumber"},
	{"2", "Два", "two.wav", "cpnumber"},
	{"200", "Двести", "twohundred.wav", "cpnumber"},
	{"нежить", "Нежить", "undead.wav", "cpcode"},
	{"союз", "Союз", "union.wav", "cpcode"},
	{"10-8", "Заступил на службу, 10-8", "unitisonduty10-8.wav", "cpstatus"},
	{"порог", "Порог", "vice.wav", "cpcode"},
	{"виктор", "Виктор", "victor.wav", "cpcode"},
	{"контакт1", "Визуальный контакт", "visualcontact.wav", "cpcombat"},
	{"ожидайте", "Ожидайте", "wait.wav", "cporder"},
	{"ожидай", "Ожидай", "wait2.wav", "cporder"},
	{"осторожно!", "Осторожно!", "watchit.wav", "cpcombat"},
	{"осторожно1", "ОСТОРОЖНО", "watchit2.wav", "cpcombat"},
	{"белый", "Белый", "white.wav", "cpcode"},
	{"рентген", "Рентген", "xray.wav", "cpcode"},
	{"желтый", "Жёлтый", "yellow.wav", "cpcode"},
	{"участок", "Что, в участок захотелось?", "youwantamalcomplianceverdict.wav", "cporder"},
	{"зона", "Зона", "zone.wav", "cpcode"},
}

for _, data in ipairs(lines) do
	NETWORK.voice.Register(data[1], {
		text = data[2],
		sound = PATH .. data[3],
		category = data[4],
		faction = "cp"
	})
end
