local PATH = "framework/vo/wallhammer/"

NETWORK.voice.RegisterCategory("whmove", "voiceWHMove")
NETWORK.voice.RegisterCategory("whcombat", "voiceWHCombat")
NETWORK.voice.RegisterCategory("whenemy", "voiceWHEnemy")
NETWORK.voice.RegisterCategory("whkill", "voiceWHKill")
NETWORK.voice.RegisterCategory("whcode", "voiceWHCode")
NETWORK.voice.RegisterCategory("whidle", "voiceWHIdle")

local lines = {
	{"двигаюсь", "Двигаюсь", "advancing_on_target_01.wav", "whmove"},
	{"выдвигаюсь2", "Выдвигаюсь", "advancing_on_target_02.wav", "whmove"},
	{"подавляю", "Подавляю", "advancing_on_target_03.wav", "whmove"},
	{"к цели", "Приближаюсь к цели", "advancing_on_target_04.wav", "whmove"},
	{"сбрасывай", "Сбрасывай", "getback_01.wav", "whmove"},
	{"боевая готовность", "Боевая готовность", "announceattack_01.wav", "whcombat"},
	{"атакуем", "Атакуем", "announceattack_02.wav", "whcombat"},
	{"цель атакована", "Цель атакована", "announceattack_03.wav", "whcombat"},
	{"устранение укрытия", "Устранение укрытия", "announceattack_cover_01.wav", "whcombat"},
	{"квадрат", "Квадрат: взлом в секторе", "announceattack_cover_02.wav", "whcombat"},
	{"вышибала", "Бросаю вышибалу!", "announceattack_grenade_01.wav", "whcombat"},
	{"бросаю гранату", "Бросаю гранату", "announceattack_grenade_02.wav", "whcombat"},
	{"извлекатель", "Извлекатель пущен", "announceattack_grenade_03.wav", "whcombat"},
	{"уклоняюсь", "Уклоняюсь", "danger_grenade_01.wav", "whcombat"},
	{"граната!2", "Граната!", "danger_grenade_02.wav", "whcombat"},
	{"молот атакует", "Молотоборец атакует", "firing_03.wav", "whcombat"},
	{"зачищаю сектор", "Зачищаю сектор", "firing_08.wav", "whcombat"},
	{"веду огонь", "Атакую, веду огонь", "firing_111.wav", "whcombat"},
	{"держу позицию", "Держу позицию", "overwatch_01.wav", "whcombat"},
	{"наблюдаю за последней", "Наблюдаю за последней известной", "overwatch_05.wav", "whcombat"},
	{"перезаряжаюсь", "Перезаряжаюсь", "reload_01.wav", "whcombat"},
	{"смена", "Смена", "switching_weapons_02.wav", "whcombat"},
	{"шипы", "Шипы близко, урона нет", "takingfire_01.wav", "whcombat"},
	{"не тронут", "Молотоборец не тронут", "takingfire_06.wav", "whcombat"},
	{"преимущество", "Использовать преимущество", "taunt_030.wav", "whcombat"},
	{"отказ", "Нет", "unabletocommence_03.wav", "whcombat"},
	{"контакт!", "Контакт", "underattack_03.wav", "whcombat"},
	{"прекратить огонь", "Прекратить огонь, это союзник!", "fakeout_responseceasefire_01.wav", "whcombat"},
	{"опустить молот", "Опустить молот, молотоборец оставляет позицию", "fakeout_responseceasefire_02.wav", "whcombat"},
	{"муравьиный лев", "Муравьиный лев", "announceenemy_antlion_01.wav", "whenemy"},
	{"цель лев", "Цель: муравьиный лев", "announceenemy_antlion_02.wav", "whenemy"},
	{"паразиты2", "Паразиты", "announceenemy_headcrabs_01.wav", "whenemy"},
	{"контакт паразиты", "Контакт: паразиты", "announceenemy_headcrabs_02.wav", "whenemy"},
	{"мёртвые", "Мёртвые", "announceenemy_zombie_01.wav", "whenemy"},
	{"поблизости мёртвые", "Поблизости мёртвые", "announceenemy_zombie_02.wav", "whenemy"},
	{"неприятели", "Неприятели", "calloutentity_hostiles_01.wav", "whenemy"},
	{"некротики", "Мёртвые", "calloutentity_necrotic_01.wav", "whenemy"},
	{"паразитики", "Паразиты", "calloutentity_parasitic_01.wav", "whenemy"},
	{"молотоборец", "Молотоборец", "calloutentity_wallhammer_01.wav", "whenemy"},
	{"звуковой", "Звуковой в секторе", "hear_suspicious_01.wav", "whenemy"},
	{"активные неприятели", "Вас понял, активные неприятели.", "hear_suspicious_03.wav", "whenemy"},
	{"неприятель убит", "Неприятель убит", "announcekill_01.wav", "whkill"},
	{"цель убита", "Цель убита", "announcekill_02.wav", "whkill"},
	{"подтверждено", "Убийство подтверждено", "announcekill_03.wav", "whkill"},
	{"лев убит", "Лев убит", "announcekill_antlion_01.wav", "whkill"},
	{"паразит зачищен", "Зачищен один паразит", "announcekill_headcrab_01.wav", "whkill"},
	{"цель сдержана", "Цель особой значимости сдержана", "announcekill_player_01.wav", "whkill"},
	{"альфа", "Альфа", "calloutcode_alpha_01.wav", "whcode"},
	{"код и", "и", "calloutcode_and_01.wav", "whcode"},
	{"браво", "Браво", "calloutcode_bravo_01.wav", "whcode"},
	{"чарли", "Чарли", "calloutcode_charlie_01.wav", "whcode"},
	{"земля", "Земля", "calloutcode_dash_01.wav", "whcode"},
	{"к8", "8", "calloutcode_eight_01.wav", "whcode"},
	{"к11", "11", "calloutcode_eleven_01.wav", "whcode"},
	{"к15", "15", "calloutcode_fifty_01.wav", "whcode"},
	{"к5", "5", "calloutcode_five_01.wav", "whcode"},
	{"к40", "40", "calloutcode_forty_01.wav", "whcode"},
	{"к4", "4", "calloutcode_four_01.wav", "whcode"},
	{"к100", "100", "calloutcode_hundred_01.wav", "whcode"},
	{"к9", "9", "calloutcode_niner_01.wav", "whcode"},
	{"к0", "0", "calloutcode_null_01.wav", "whcode"},
	{"к1", "1", "calloutcode_one_01.wav", "whcode"},
	{"сектор2", "Сектор", "calloutcode_sector_01.wav", "whcode"},
	{"грузовик", "Грузовик", "calloutlocation_truck_01.wav", "whcode"},
	{"лестница", "Лестница", "calloutlocation_woodpile_01.wav", "whcode"},
	{"рекомендую подготовку", "Патруль, у нас активные неприятели, рекомендую подготовку!", "combat_idle_010.wav", "whidle"},
	{"цель активна", "Никак нет. Цель всё ещё активна.", "combat_idle_020.wav", "whidle"},
	{"состояние альфа", "Вас понял, выстраиваю состояние Альфа.", "combat_idle_030.wav", "whidle"},
	{"ожидаю приказа", "Ожидаю приказа о выдвижении, приём", "combat_idle_040.wav", "whidle"},
	{"рекалибровка", "Подтверждено, рекалибровка", "combat_idle_050.wav", "whidle"},
	{"занимаю позицию", "Принято. Занимаю позицию.", "combat_idle_060.wav", "whidle"},
	{"ещё живы", "Они всё ещё живы", "combat_idle_070.wav", "whidle"},
	{"сдерживание", "Вас понял, реализуем сдерживание и контроль", "combat_idle_080.wav", "whidle"},
	{"10-42", "10-4, отбой: кинжалы закреплены и готовы к бою.", "combat_idle_100.wav", "whidle"},
	{"био-данные", "Ожидаю загрузки био-данных", "combat_idle_131.wav", "whidle"},
	{"докладывать нечего", "Докладывать нечего, приём.", "idle_01.wav", "whidle"},
	{"изоляция сектора", "Патруль подтверждает изоляцию сектора: держать оборону и слушать!", "idle_09.wav", "whidle"},
	{"ещё здесь", "Принято, ещё здесь.", "idle_16.wav", "whidle"},
	{"дыхание", "*Дыхание*", "breathing_01.wav", "whidle"},
	{"дыхание22", "*Дыхание*", "breathing_02.wav", "whidle"},
	{"смех", "*Смех*", "laugh_01.wav", "whidle"},
	{"смех2", "*Смех*", "laugh_02.wav", "whidle"},
	{"крик", "*Крик*", "stunned_rollerball_05.wav", "whidle"},
	{"последний", "Патруль, молотоборец последний, запрашиваю помощь", "squadmemberlost_lastman_02.wav", "whidle"},
}

for _, data in ipairs(lines) do
	NETWORK.voice.Register(data[1], {
		text = data[2],
		sound = PATH .. data[3],
		category = data[4],
		faction = "cmb",
		class = "wallhammer"
	})
end
